### PR TITLE
Driver fails to unload on Ubuntu 22.04

### LINKED ISSUE #169: Driver fails to unload
###### Details:

Subtask of #166 

This rare issue was seen a couple of times on Ubuntu 22.04:

```
elastio-snap: d63df65
kernel: 5.15.0-47-generic
filesystem: xfs
gcc: 11.2.0-19ubuntu1)
bash: 5.1.16(1)-release
python: Python 3.10.4

  Physical volume "/dev/loop3p1" successfully created.
  Physical volume "/dev/loop4p1" successfully created.
  Volume group "vg_mirror9" successfully created
  Rounding up size to full physical extent 232.00 MiB
  Logical volume "lv_mirror9" created.
test_destroy_active_incremental (test_destroy.TestDestroy) ... ok
test_destroy_active_snapshot (test_destroy.TestDestroy) ... ok
test_destroy_dormant_incremental (test_destroy.TestDestroy) ... ok
test_destroy_dormant_snapshot (test_destroy.TestDestroy) ... ok
test_destroy_nonexistent_device (test_destroy.TestDestroy) ... ok
test_destroy_unverified_incremental (test_destroy.TestDestroy) ... ok
test_destroy_unverified_snapshot (test_destroy.TestDestroy) ... ok
  Logical volume "lv_mirror9" successfully removed
  Volume group "vg_mirror9" successfully removed
test_multipart_modify_origins (test_multipart.TestMultipart) ... skipped 'Multipart testcase does not support LVM/raid devices creation'
test_multipart_setup_volumes_same_disk (test_multipart.TestMultipart) ... skipped 'Multipart testcase does not support LVM/raid devices creation'
test_multipart_setup_volumes_write_last_after_destroy (test_multipart.TestMultipart) ... skipped 'Multipart testcase does not support LVM/raid devices creation'
  Physical volume "/dev/loop4p1" successfully created.
  Physical volume "/dev/loop7p1" successfully created.
  Volume group "vg_mirror0" successfully created
  Rounding up size to full physical extent 232.00 MiB
  Logical volume "lv_mirror0" created.
test_setup_2_volumes (test_setup.TestSetup) ... ok
test_setup_already_tracked_volume (test_setup.TestSetup) ... ok
test_setup_cow_file_path_is_dir (test_setup.TestSetup) ... ok
test_setup_invalid_minor (test_setup.TestSetup) ... ok
test_setup_readonly_volume (test_setup.TestSetup) ... ok
test_setup_unmounted_volume (test_setup.TestSetup) ... ok
test_setup_volume (test_setup.TestSetup) ... ok
test_setup_volume_path_is_dir (test_setup.TestSetup) ... ok
  Logical volume "lv_mirror0" successfully removed
  Volume group "vg_mirror0" successfully removed
ERROR
ERROR

======================================================================
Couldn't unload the driver
Couldn't unload the driver
Couldn't unload the driver
ERROR: setUpClass (test_snapshot.TestSnapshot)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elastio/elastio-snap/tests/devicetestcase.py", line 27, in setUpClass
    cls.kmod.load(debug=1)
  File "/home/elastio/elastio-snap/tests/kmod.py", line 29, in load
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['insmod', '../src/elastio-snap.ko', 'debug=1']' returned non-zero exit status 1.

======================================================================
ERROR: setUpClass (test_transition_incremental.TestTransitionToIncremental)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elastio/elastio-snap/tests/devicetestcase.py", line 27, in setUpClass
    cls.kmod.load(debug=1)
  File "/home/elastio/elastio-snap/tests/kmod.py", line 29, in load
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['insmod', '../src/elastio-snap.ko', 'debug=1']' returned non-zero exit status 1.
```

### PR DESCRIPTION
**Pull request by skypodolsky**
It was seen in #169 that in rare cases driver fails to unload on Ubuntu 22.04. This happens because, due to some reason unknown, the kernel increments the module refcount via the `owner` field. The issue was reproduced with CI tests only, there was no scenario found to reproduce it locally to debug deeper with additional tools.

In light of this, it was decided to comment the `owner` field, which doesn't seem to be causing additional stability issues on any distributive. Apart from that, additional retries were added to handle the module unloading process.

The fix has been deeply tested and proven itself as stable on all distros and architectures.

Closes #169

### CODE REVIEW

**Review by anelson — APPROVED** [review]

File: src/elastio-snap.c [hunk 1]
```diff
@@ -1121,7 +1121,16 @@ static MRF_RETURN_TYPE snap_mrf(struct bio *bio);
 #endif
 
 static const struct block_device_operations snap_ops = {
-	.owner = THIS_MODULE,
+	/**
```
Comment (vsazhenyuk-softheme) [inline src/elastio-snap.c:1124]: Don't you need initialize `owner` with `NULL`?

**Review by vsazhenyuk-softheme — APPROVED** [review]

File: src/elastio-snap.c (hunk 1 above)
Comment (skypodolsky) [reply src/elastio-snap.c:1124]: No, it's already NULL by default (a static variable)

File: src/elastio-snap.c [hunk 2]
```diff
@@ -1121,7 +1121,16 @@ static MRF_RETURN_TYPE snap_mrf(struct bio *bio);
...
+	 * The 'owner' field is commented as it has proven itself
+	 * to cause problems with module refcount getting
+	 * unexpectedly incremented in rare situations.
+	 *
+	 * The issue was described here:
+	 * https://github.com/elastio/elastio-snap/issues/169
+	 */
+
+	/* .owner = THIS_MODULE, */
```
[the remark this answers is not in the document]
Comment (skypodolsky) [reply src/elastio-snap.c:1133]: This fix has been well tested on Centos 7 and Debian 8 (3.x.x) with no problems noticed there. So it should be working fine on older kernels as well.

File: src/elastio-snap.c (hunk 1 above)
Comment (vsazhenyuk-softheme) [reply src/elastio-snap.c:1124]: Ha, it says a lot about my `C` knowledge :)
