### PR TITLE
test_transition_fs_sync_cow_full fails on fedora 35

### LINKED ISSUE #170: test_transition_fs_sync_cow_full fails on fedora 35
###### Details:

```
test_destroy_active_incremental (test_destroy.TestDestroy) ... ok
test_destroy_active_snapshot (test_destroy.TestDestroy) ... ok
test_destroy_dormant_incremental (test_destroy.TestDestroy) ... ok
test_destroy_dormant_snapshot (test_destroy.TestDestroy) ... ok
test_destroy_nonexistent_device (test_destroy.TestDestroy) ... ok
test_destroy_unverified_incremental (test_destroy.TestDestroy) ... ok
test_destroy_unverified_snapshot (test_destroy.TestDestroy) ... ok
test_multipart_modify_origins (test_multipart.TestMultipart) ... skipped 'Multipart testcase requires disk, not a partition.'
test_multipart_setup_volumes_same_disk (test_multipart.TestMultipart) ... skipped 'Multipart testcase requires disk, not a partition.'
test_multipart_setup_volumes_write_last_after_destroy (test_multipart.TestMultipart) ... skipped 'Multipart testcase requires disk, not a partition.'
test_setup_2_volumes (test_setup.TestSetup) ... ok
test_setup_already_tracked_volume (test_setup.TestSetup) ... ok
test_setup_cow_file_path_is_dir (test_setup.TestSetup) ... ok
test_setup_invalid_minor (test_setup.TestSetup) ... ok
test_setup_readonly_volume (test_setup.TestSetup) ... ok
test_setup_unmounted_volume (test_setup.TestSetup) ... ok
test_setup_volume (test_setup.TestSetup) ... ok
test_setup_volume_path_is_dir (test_setup.TestSetup) ... ok
test_modify_origin (test_snapshot.TestSnapshot) ... ok
test_next_available_minor (test_snapshot.TestSnapshot) ... ok
test_track_writes (test_snapshot.TestSnapshot) ... ok
test_transition_active_incremental (test_transition_incremental.TestTransitionToIncremental) ... ok
test_transition_active_snapshot (test_transition_incremental.TestTransitionToIncremental) ... ok
test_transition_fs_sync_cow_full (test_transition_incremental.TestTransitionToIncremental) ... FAIL
test_transition_mod_sync_cow_full (test_transition_incremental.TestTransitionToIncremental) ... skipped 'Kernel flushed before module'
test_transition_nonexistent_snapshot (test_transition_incremental.TestTransitionToIncremental) ... ok

======================================================================
FAIL: test_transition_fs_sync_cow_full (test_transition_incremental.TestTransitionToIncremental)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elastio/elastio-snap/tests/test_transition_incremental.py", line 58, in test_transition_fs_sync_cow_full
    self.assertTrue(err == errno.EINVAL or err == errno.EFBIG)
AssertionError: False is not true
```

### PR DESCRIPTION
**Pull request by skypodolsky**
It was seen that at the time when ioctl (transition to incremental) takes place, we still got some unprocessed bio in snap_cow_thread(). As the solution, it is proposed to add some wait in ioctl handlers to make sure all bio requests have been processed.

Here is the log explaining the behavior previously observed. Please take a look at the counters of the received (queued) and processed bio requests:

```
[  461.946031] elastio-snap: ioctl command received: 1074020613 
[  461.946033] elastio-snap: received transition inc ioctl - 19
[  461.946034] elastio-snap:    >> WAITING STARTED (bio received=61, bio processed=48)...
[  461.946759] elastio-snap: error handling write bio in kernel thread: -27
[  461.946034] elastio-snap:    >> WAITING FINISHED (bio received=61, bio processed=61)...
[  462.460080] elastio-snap: device specified is in the fail state: -27
[  462.461223] elastio-snap: error during transition to incremental ioctl handler: -27
[  462.462313] elastio-snap: minor range = 19 - 19
```

Closes #170

### CODE REVIEW

File: src/elastio-snap.c [hunk 1]
```diff
@@ -3344,6 +3346,15 @@ static void __on_bio_read_complete(struct bio *bio, int err){
 	bio_free_clone(bio);
 }
 
+static inline void wait_for_bio_complete(struct snap_device *dev)
+{
+	struct bio_queue *bq = &dev->sd_cow_bios;
```
Comment (anelson) [inline src/elastio-snap.c:3351]: I'd like to see a comment here linking to the Github issue this is resolving.

**Review by anelson — COMMENTED** [review]
Minor comment

File: src/elastio-snap.c (hunk 1 above)
Comment (vsazhenyuk-softheme) [reply src/elastio-snap.c:3351]: @anelson I don't think any comments are necessary: this PR implement a missing piece of functionality, which should be here despite any issues found.

**Review by vsazhenyuk-softheme — APPROVED** [review]

File: src/elastio-snap.c [hunk 2]
```diff
@@ -3344,6 +3346,15 @@ static void __on_bio_read_complete(struct bio *bio, int err){
...
+	if (atomic64_read(&dev->sd_received_cnt) != atomic64_read(&dev->sd_processed_cnt))
+		wait_event_interruptible_timeout(bq->event,
+				atomic64_read(&dev->sd_submitted_cnt) == atomic64_read(&dev->sd_processed_cnt),
+				msecs_to_jiffies(500));
```
Comment (e-kov) [inline src/elastio-snap.c:3355]: The conditions in `if` and in the `wait_event_interruptible_timeout` are different. Discussed it with @skypodolsky offline. The code will be changed.

File: src/elastio-snap.c [hunk 3]
```diff
@@ -4913,6 +4930,7 @@ static int ioctl_elastio_snap_info(struct elastio_snap_info *info){
 	if(ret) goto error;
 
 	dev = snap_devices[info->minor];
+	wait_for_bio_complete(dev);
```
Comment (e-kov) [inline src/elastio-snap.c:4933]: `ioctl_elastio_snap_info` is called by `elastio` CLI many times in a row during snapshot. As I understood, this change allows to get response with an error, if it just appeared. And a small delay in response doesn't harm. And it will not affect performance of the snapshot read operations.
@skypodolsky please correct me, if I'm wrong.

File: src/elastio-snap.c (hunk 2 above)
Comment (skypodolsky) [reply src/elastio-snap.c]: Exactly, this has been fixed.

File: src/elastio-snap.c (hunk 3 above)
Comment (skypodolsky) [reply src/elastio-snap.c]: This is correct. Nevertheless, I decided to remove `wait_for_bio_complete()` to improve the response time if the system is overloaded with bio requests.

File: src/elastio-snap.c [hunk 4]
```diff
@@ -3344,6 +3346,14 @@ static void __on_bio_read_complete(struct bio *bio, int err){
 	bio_free_clone(bio);
 }
 
+static inline void wait_for_bio_complete(struct snap_device *dev)
+{
+	struct bio_queue *bq = &dev->sd_cow_bios;
+	wait_event_interruptible_timeout(bq->event,
+			atomic64_read(&dev->sd_submitted_cnt) == atomic64_read(&dev->sd_processed_cnt),
+			msecs_to_jiffies(500));
```
Comment (e-kov) [inline src/elastio-snap.c:3354]: What do you think about to put `#define WAIT_SUBMITTED_BIOS_MS 500` somewhere above and log a warning about timeout?

```suggestion
	int ret;

	ret = wait_event_interruptible_timeout(bq->event,
			atomic64_read(&dev->sd_submitted_cnt) == atomic64_read(&dev->sd_processed_cnt),
			msecs_to_jiffies(WAIT_SUBMITTED_BIOS_MS));
	if (!ret) {
		LOG_WARN("failed wait for all submitted BIOs to be processed after %d ms. bio submitted = %lld, bio processed = %lld", WAIT_SUBMITTED_BIOS_MS, atomic64_read(&dev->sd_submitted_cnt), atomic64_read(&dev->sd_processed_cnt));
	}
```

File: src/elastio-snap.c (hunk 1 above)
Comment (anelson) [reply src/elastio-snap.c:3351]: I disagree.  This was missing for years and we noticed it only in a minor test failure on one distro.  It's clearly not obvious.

Comment (skypodolsky) [reply src/elastio-snap.c:3353]: @anelson done

File: src/elastio-snap.c (hunk 4 above)
Comment (skypodolsky) [reply src/elastio-snap.c]: Done

**Review by anelson — APPROVED** [review]

**Review by e-kov — APPROVED** [review]
