### PR TITLE
Wait for snap release after IOCTL_SETUP_SNAP handling

### LINKED ISSUE #26: Failed to destroy snapshot immediately after taking it
Spinof of https://github.com/elastio/assurio/pull/201 issue in assurio repository.
If we run this script with commands for driver cli

```
aioctl setup-snapshot /dev/sda4 "/home/cow0.bin" 0
aioctl destroy 0
```
 it fails with 
```
from /var/log/syslog:
May 15 10:39:31 osboxes kernel: [ 2556.577899] assurio-snap: device specified is busy: -16
May 15 10:39:31 osboxes kernel: [ 2556.577904] assurio-snap: error during destroy ioctl handler: -16
```
I did it for 270 Gb volume.

### PR DESCRIPTION
**Pull request by alexxxsereda**
After the snap setup we got to wait for interruptible timeout
till (busy state) atomic lock would be released.

Closes #26

### CODE REVIEW

**Review by e-kov — APPROVED** [review]

File: src/elastio-snap.c [hunk 1]
```diff
@@ -1003,6 +1004,11 @@ static void elastio_snap_proc_stop(struct seq_file *m, void *v);
 static int elastio_snap_proc_open(struct inode *inode, struct file *filp);
 static int elastio_snap_proc_release(struct inode *inode, struct file *file);
 
+// wait msec value to be at least 100 msec as wait loop uses it by msleep of (100) timeout pieces
+#define ELASTIO_SNAP_WAIT_FOR_RELEASE_MSEC              500
+#define ELASTIO_SNAP_WAIT_FOR_RELEASE_TIMEOUT_PEICE_CNT 100
```
Comment (anelson) [inline src/elastio-snap.c:1009]: I think this is an error, you meant to write `PIECE`, but even spelled correctly it's not clear what this means.  I think something better would be:

```suggestion
#define ELASTIO_SNAP_WAIT_FOR_RELEASE_MAX_SLEEP_COUNT 100
```

**Review by anelson — APPROVED** [review]
Approved conditional upon addressing the comment I made in the PR.
