### PR TITLE
Provide support of the direct IO functionality for all Linux kernel versions

### LINKED ISSUE #219: Implement the support of direct device IO operations
A potentially dangerous scenario has been found and is related to the dormant snapshot functionality.

Briefly on it. When the driver is operating and the device is being snapshotted, there is a legal possibility to unmount it from the system to run some maintenance or diagnostics. When this happens, the elastio-snap driver is able to handle this case by switching the snapshot device to the so-known 'dormant', or unmounted state, where tracing of file operations and hence no COW takes place. To do this, the driver has mount/umount hooks set up: when the device is unmounted, we first run the driver's handler, then call the original system umount function afterward. When deinitialized, no COW thread is running, so no new bio requests can be processed. The device is waiting to be mounted again to restart the block IO tracing.

It's been verified though that additional bio requests are generated when the device is unmounted. This happens due to the sync & journaling operations. As we remember, the dormant snapshot state assumes there would be no operations to the block device, so this case leads us to the conflict situation when some of the bio requests cannot be traced and backed up by the driver. Moreover, some of the bio requests cannot be processed by the elastio-snap as the snap COW thread is stopped. Normally these bios wait for the device to be mounted again, but if we shut down the system in that state, some data will be lost irreversibly.

There were several approaches to cope with this problem, but no one has proven the efficacy as the principal problem remains the same: we kill the COW thread before ALL bio requests related to the device unmount are processed. But if we move the COW thread stop after the umount is handled, then no COW file exists on the disk anymore (as it is simply not mounted) and no tracing is possible anyway.

The use case including the system shut down is deeply important for the elastio-snap driver to assure the file system stability and data integrity. Hence, in order to suggest a solution, a deep investigation has been performed.

According to it, the proposed design includes the following:
 - As we can't write with the typical kernel functions (`vfs_write()`/`kernel_write()`) when the device is unmounted, we need to implement the support of read/write disk IO. This will be done with help of file extents provided by `FIEMAP` ioctl. This part has been verified during the investigation;
 - We must be sure these extents are properly synced in the driver (f.e., due to the truncation (being done on the transition to the incremental mode) or disk maintenance the COW file may be defragmented and occupy different sectors on the disk) to make sure we won't rewrite anything else. This part has been also worked out already;
 - Consequently, as we obtain the raw file sectors, we must provide a proper mapping of the new COW blocks to the existing ones to make sure the structure of the COW file remains alright;
 - Last but not least, we need to reconsider the logic of the dormant snapshot mode to make sure we write ALL changes to the disk (even after it's been unmounted) BEFORE the COW thread is stopped

This sounds like a hell of a job and a major reconsideration of some pieces in the driver, so this is why this epic is here. But this needs to be done to ensure data integrity as this is the most important aspect we must focus on.

### LINKED ISSUE #226: Provide support of the direct IO functionality for all Linux kernel versions
The current implementation has been implemented and tested on the 5.4 kernel (Ubuntu 20.04). It is known that fiemap-related functionality doesn't work on the 6.1 kernel. Apart from that, current code needs to be aligned with kernel symbols that change from version to version (such as `vm_area_alloc()`)

This relates to the epic #219

### LINKED ISSUE #228: Fiemap doesn't work with XFS
OS: Ubuntu 20.04, Debian 9

For some reason, fiemap (which is supported by the xfs filesystem) doesn't return the file extents

Blocks #227

### LINKED ISSUE #229: Sometimes test_reload fails on test_reload_verified_inc
It's sometimes seen that during elio-test.sh the driver fails on `umount` with the following kernel panic:

```
[   61.655725] BUG: unable to handle page fault for address: 0000000000001000
[   61.655753] #PF: supervisor read access in kernel mode
[   61.655765] #PF: error_code(0x0000) - not-present page
[   61.655778] PGD 0 P4D 0
[   61.655793] Oops: 0000 [#1] SMP NOPTI
[   61.655805] CPU: 3 PID: 2147 Comm: umount Tainted: G           OE     5.4.0-110-generic #124-Ubuntu
[   61.655826] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.13.0-1ubuntu1.1 04/01/2014
[   61.655850] RIP: 0010:file_write_block.cold+0x29/0x122 [elastio_snap]
[   61.655866] Code: ff 48 8b 55 d0 4c 89 fe 48 c7 c7 f0 ad aa c0 e8 c4 27 fe f6 49 8b 4f 68 48 85 c9 74 67 83 3d 38 79 00 00 00 0f 84 cf b1 ff ff <48> 8b 31 48 c7 c7 b5 d0 aa c0 e8 9f 27 fe f6 49 8b 4f 68 e9 b7 b1
[   61.655903] RSP: 0018:ffff9def80b8bdd0 EFLAGS: 00010202
[   61.655919] RAX: 0000000000000053 RBX: 0000000000001000 RCX: 0000000000001000
[   61.655934] RDX: 0000000000000000 RSI: 0000000000000082 RDI: ffff91866fadc8c0
[   61.655949] RBP: ffff9def80b8be18 R08: 0000000000000d51 R09: 0000000000000004
[   61.655964] R10: 0000000000000000 R11: 0000000000000001 R12: 0000000000000000
[   61.655980] R13: 0000000000000008 R14: 0000000000000000 R15: ffff918659091400
[   61.655997] FS:  00007f0c1815f840(0000) GS:ffff91866fac0000(0000) knlGS:0000000000000000
[   61.656015] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   61.656028] CR2: 0000000000001000 CR3: 000000042b528000 CR4: 0000000000340ee0
[   61.656045] Call Trace:
[   61.656065]  ? vprintk_func+0x4c/0xc0
[   61.656078]  __cow_sync_and_free_sections+0x7b/0xe0 [elastio_snap]
[   61.656093]  __tracer_destroy_cow+0xbf/0x1d0 [elastio_snap]
[   61.656107]  handle_bdev_mount_event+0x202/0x2b0 [elastio_snap]
[   61.656123]  umount_hook+0x93/0x110 [elastio_snap]
[   61.656140]  do_syscall_64+0x57/0x190
[   61.656161]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[   61.656173] RIP: 0033:0x7f0c183be16b
[   61.656184] Code: cd 0c 00 f7 d8 64 89 01 48 83 c8 ff c3 66 90 f3 0f 1e fa 31 f6 e9 05 00 00 00 0f 1f 44 00 00 f3 0f 1e fa b8 a6 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d f5 cc 0c 00 f7 d8 64 89 01 48
[   61.656220] RSP: 002b:00007ffd6f0b6b68 EFLAGS: 00000246 ORIG_RAX: 00000000000000a6
[   61.656237] RAX: ffffffffffffffda RBX: 00007f0c184f0204 RCX: 00007f0c183be16b
[   61.656252] RDX: 0000000000000000 RSI: 0000000000000000 RDI: 000056010dc8ac40
[   61.656268] RBP: 000056010dc8aa30 R08: 0000000000000000 R09: 00007ffd6f0b5910
[   61.656292] R10: 00007f0c184dc379 R11: 0000000000000246 R12: 000056010dc8ac40
[   61.656308] R13: 0000000000000000 R14: 000056010dc8ab28 R15: 0000000000000000
[   61.656324] Modules linked in: elastio_snap(OE) xt_conntrack xt_MASQUERADE nf_conntrack_netlink nfnetlink xfrm_user xfrm_algo xt_addrtype iptable_filter iptable_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 bpfilter br_netfilter bridge stp llc aufs overlay binfmt_misc dm_multipath scsi_dh_rdac scsi_dh_emc scsi_dh_alua joydev input_leds kvm_amd ccp mac_hid serio_raw kvm qemu_fw_cfg sch_fq_codel msr ip_tables x_tables autofs4 btrfs zstd_compress raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq libcrc32c raid1 raid0 multipath linear crct10dif_pclmul crc32_pclmul ghash_clmulni_intel virtio_net net_failover failover cirrus drm_kms_helper aesni_intel syscopyarea sysfillrect crypto_simd sysimgblt fb_sys_fops drm cryptd glue_helper psmouse virtio_blk pata_acpi i2c_piix4 floppy [last unloaded: elastio_snap]
[   61.656493] CR2: 0000000000001000
[   61.656506] ---[ end trace d1df488f6a4d14fe ]---
[   61.657073] RIP: 0010:file_write_block.cold+0x29/0x122 [elastio_snap]
[   61.657629] Code: ff 48 8b 55 d0 4c 89 fe 48 c7 c7 f0 ad aa c0 e8 c4 27 fe f6 49 8b 4f 68 48 85 c9 74 67 83 3d 38 79 00 00 00 0f 84 cf b1 ff ff <48> 8b 31 48 c7 c7 b5 d0 aa c0 e8 9f 27 fe f6 49 8b 4f 68 e9 b7 b1
[   61.658772] RSP: 0018:ffff9def80b8bdd0 EFLAGS: 00010202
[   61.659335] RAX: 0000000000000053 RBX: 0000000000001000 RCX: 0000000000001000
[   61.659906] RDX: 0000000000000000 RSI: 0000000000000082 RDI: ffff91866fadc8c0
[   61.660497] RBP: ffff9def80b8be18 R08: 0000000000000d51 R09: 0000000000000004
[   61.660984] R10: 0000000000000000 R11: 0000000000000001 R12: 0000000000000000
[   61.661272] R13: 0000000000000008 R14: 0000000000000000 R15: ffff918659091400
[   61.661556] FS:  00007f0c1815f840(0000) GS:ffff91866fac0000(0000) knlGS:0000000000000000
[   61.661840] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   61.662119] CR2: 0000000000001000 CR3: 000000042b528000 CR4: 0000000000340ee0
[   61.668460] elastio-snap: detected block device umount: /tmp/elastio-snap_010 : 0
[   61.669177] elastio-snap: block device umount detected for device 10
```

Despite this happens on ext4 and xfs (other filesystems were not verified), the xfs seems to facilitate the reproduce. Probably, the `sd_cow` pointer is corrupted when switching to the incremental mode.

### LINKED ISSUE #230: Two consecutive tests test_reload_verified_inc + test_reload_verified_snapshot fail
```
[ 5956.548801] attempt to access beyond end of device
               loop13: rw=2048, want=7, limit=524288
[ 5956.548802] elastio-snap: submit_bio_wait() error!: -5
[ 5956.549148] elastio-snap: error reading cow data: -5
[ 5956.549426] elastio-snap: error handling read bio: -5
[ 5956.549706] elastio-snap: error handling read bio in kernel thread: -5
[ 5956.550039] Buffer I/O error on dev elastio-snap9, logical block 0, async page read
[ 5956.550409] Buffer I/O error on dev elastio-snap9, logical block 1, async page read
```

This only happens with XFS when `tests test_reload_verified_inc` + `test_reload_verified_snapshot` are called consecutively. Presumably, this relates to the invalid section content.

Relates to the epic #219

### LINKED ISSUE #231: Reading large file through snap_handle_read_bio() doesn't work with ext2/ext3

### LINKED ISSUE #232: test_transition_fs_sync_cow_full fails on XFS
```
[elastio@centos7-amd64-test tests]$ sudo -E python3 -m unittest -v test_transition_incremental.TestTransitionToIncremental.test_transition_fs_sync_cow_full
  WARNING: Device for PV 12uxEk-KVwo-NWoG-QdeB-E9kV-50nu-MCyB1w not found or rejected by a filter.
  WARNING: Device for PV r1K9gZ-liKS-eYs4-4k0R-eVzC-wcyc-1d9My5 not found or rejected by a filter.
  WARNING: Device for PV 12uxEk-KVwo-NWoG-QdeB-E9kV-50nu-MCyB1w not found or rejected by a filter.
  WARNING: Device for PV r1K9gZ-liKS-eYs4-4k0R-eVzC-wcyc-1d9My5 not found or rejected by a filter.
  Physical volume "/dev/loop3p1" successfully created.
  Physical volume "/dev/loop4p1" successfully created.
  WARNING: Device for PV 12uxEk-KVwo-NWoG-QdeB-E9kV-50nu-MCyB1w not found or rejected by a filter.
  WARNING: Device for PV r1K9gZ-liKS-eYs4-4k0R-eVzC-wcyc-1d9My5 not found or rejected by a filter.
  WARNING: Device for PV 12uxEk-KVwo-NWoG-QdeB-E9kV-50nu-MCyB1w not found or rejected by a filter.
  WARNING: Device for PV r1K9gZ-liKS-eYs4-4k0R-eVzC-wcyc-1d9My5 not found or rejected by a filter.
  Volume group "vg_mirror12" successfully created
  Rounding up size to full physical extent 232.00 MiB
  Logical volume "lv_mirror12" created.
test_transition_fs_sync_cow_full (test_transition_incremental.TestTransitionToIncremental) ... FAIL
  Logical volume "lv_mirror12" successfully removed
  Volume group "vg_mirror12" successfully removed

======================================================================
FAIL: test_transition_fs_sync_cow_full (test_transition_incremental.TestTransitionToIncremental)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elastio/elastio-snap/tests/test_transition_incremental.py", line 64, in test_transition_fs_sync_cow_full
    self.assertEqual(snapdev["state"], elastio_snap.State.ACTIVE | elastio_snap.State.SNAPSHOT)
AssertionError: 2 != 3

----------------------------------------------------------------------
Ran 1 test in 2.559s

FAILED (failures=1)
```

Reproduces on LVM (f.e., centos7)

Relates to the epic #219

### LINKED ISSUE #234: CentOS 8 doesn't work on arm64
`test_reload_verified_snapshot` fails, multiple kernel warnings take place

### LINKED ISSUE #235: test_modify_origin fails on Amazon 2

### PR DESCRIPTION
**Pull request by skypodolsky**
This gigantic patch finishes the development of direct IO operations and thus closes the epic.

Global changes:

* Fixed compilation on all supported kernels
* Added memory unmapping when stealing memory pages from a parent process
* Rewritten `fiemap` to use more data pages (max extents are passed with module parameter)
* Removed `test_storage_redirected.py` as unneeded
* Added more data to be snapshotted in `test_modify origin` to verify the data consistency with larger files
* Added debug information in CI tests to simplify reading logs
* Disabled lazy init in CI tests to make sure no deferred write operations will be traced (this makes tests more predictable)
* Fixed block translation issue
* Fixed data corruption on read/write when we perform an operation on the edge of a file extent (fragmented file)
* Made COW file _really_ contain specified disk data (f.e., earlier, if we specified 10% of the disk volume to be used for data storage in the snapshot mode, less than 10% was actually available for that (because of the section storage + header included))
* Replaced magic numbers in cow section allocation math

Closes #226 
Closes #228 
Closes #229 
Closes #230 
Closes #231 
Closes #232 
Closes #234 
Closes #235 
Closes #219

### CODE REVIEW

File: src/elastio-snap.c [hunk 1]
```diff
@@ -1836,23 +1840,26 @@ int file_write_block(struct snap_device *dev, void *block, size_t offset, size_t
 	bdev = dev->sd_base_dev;
 	sectors_processed = 0;
 
-	WARN_ON(!IS_ALIGNED(offset, PAGE_SIZE) || len > SECTORS_PER_BLOCK);
+	WARN_ON(len > SECTORS_PER_BLOCK);
```
Comment (skypodolsky) [inline src/elastio-snap.c:1843]: Offset may be unaligned on architectures where PAGE_SIZE is more than 4k (f.e., on CentOS 8 + aarch64, where it's 64k)

File: src/elastio-snap.c [hunk 2]
```diff
@@ -2203,6 +2211,8 @@ static int file_allocate(struct snap_device *dev, struct file *f, uint64_t offse
 	}
 
 out:
+	file_lock(f);
```
Comment (skypodolsky) [inline src/elastio-snap.c:2214]: It's correct to lock the cow file at the very end, after all zero fillings are made.

File: src/elastio-snap.c [hunk 3]
```diff
@@ -2298,13 +2308,21 @@ static int __cow_alloc_section(struct cow_manager *cm, unsigned long sect_idx, i
...
 
-	ret = __cow_alloc_section(cm, sect_idx, 0);
+	ret = __cow_alloc_section(cm, sect_idx, 1);
 	if(ret) goto error;
 
-	ret = file_read_block(cm->dev, cm->sects[sect_idx].mappings, cm->sect_size*sect_idx*8 + COW_HEADER_SIZE, SECTORS_PER_BLOCK);
-	if(ret) goto error;
+	// SECTORS_PER_BLOCK contains 512 mappings (4096 bytes / 8 bytes)
+	// sect_size is 32768 bytes containing 4096 mappings (32768 bytes / 8 bytes)
+	// hence we need to read it 8 times with a shift of 512 mappings on each iteration
```
Comment (skypodolsky) [inline src/elastio-snap.c:2318]: TODO: rewrite the comment

File: src/elastio-snap.c [hunk 4]
```diff
@@ -2315,12 +2333,20 @@ static int __cow_load_section(struct cow_manager *cm, unsigned long sect_idx){
...
-	int ret;
+	int i, ret;
 
-	ret = file_write_block(cm->dev, cm->sects[sect_idx].mappings, cm->sect_size*sect_idx*8 + COW_HEADER_SIZE, SECTORS_PER_BLOCK);
-	if(ret){
-		LOG_ERROR(ret, "error writing cow manager section to file");
-		return ret;
+	// SECTORS_PER_BLOCK contains 512 mappings (4096 bytes / 8 bytes)
+	// sect_size is 32768 bytes containing 4096 mappings (32768 bytes / 8 bytes)
+	// hence we need to write it 8 times with a shift of 512 mappings on each iteration
```
Comment (skypodolsky) [inline src/elastio-snap.c:2340]: TODO: rewrite the comment

File: src/elastio-snap.c [hunk 5]
```diff
@@ -2624,43 +2672,45 @@ static int elastio_snap_get_cow_file_extents(struct snap_device *dev, struct fil
...
 		fiemap_info.fi_flags = FIEMAP_FLAG_SYNC;
 		fiemap_info.fi_extents_mapped = 0;
-		do_div(cow_ext_buf_size, sizeof(struct fiemap_extent));
-		fiemap_info.fi_extents_max = cow_ext_buf_size;
+		do_div(max_num_extents, sizeof(struct fiemap_extent));
+		fiemap_info.fi_extents_max = max_num_extents;
 		fiemap_info.fi_extents_start = (struct fiemap_extent __user *)cow_ext_buf;
 
-		ret = fiemap(filp->f_inode, &fiemap_info, 0, FIEMAP_MAX_OFFSET);
+		ret = fiemap(filp->f_inode, &fiemap_info, 0, INT_MAX);
```
Comment (skypodolsky) [inline src/elastio-snap.c:2713]: INT_MAX is to be replaced with the max signed uint64_t number.

File: src/elastio-snap.c [hunk 6]
```diff
@@ -3723,6 +3767,8 @@ static int snap_cow_thread(void *data){
 		}
 	}
 
+	LOG_DEBUG("snap_cow_thread() done.");
```
Comment (skypodolsky) [inline src/elastio-snap.c:3770]: This is not an abandoned print, I'd like to keep it for debugging in the future.

File: tests/test_destroy.py [hunk 7]
```diff
@@ -22,6 +22,11 @@ def setUp(self):
         self.cow_reload_path = "/{}".format(self.cow_file)
         self.snap_device = "/dev/elastio-snap{}".format(self.minor)
 
+        util.test_track(self._testMethodName, started=True)
+
+    def tearDown(self):
+        util.test_track(self._testMethodName, started=False)
```
Comment (skypodolsky) [inline tests/test_destroy.py:28]: Add to the multi-partition part

File: tests/devicetestcase_multipart.py [hunk 8]
```diff
@@ -22,6 +22,8 @@ def setUpClass(cls):
         # For now let's hardcode 7 partitions
         cls.part_count = 7
         cls.minors = []
+        cls.size_mb = 256
```
Comment (skypodolsky) [inline tests/devicetestcase_multipart.py:25]: No reason to have 512MB for a couple of basic multipart tests

File: src/elastio-snap.c [hunk 9]
```diff
@@ -2813,14 +2869,47 @@ static int cow_init(struct snap_device *dev, const char *path, uint64_t elements
...
+	//  Belowe we calculate that.
+	//
+	//  Here '8' is sizeof(uint64_t) (please refer to 'struct cow_section')
+
+	cm->log_sect_pages = get_order(sect_size * 8);
 	cm->total_sects = NUM_SEGMENTS(elements, cm->log_sect_pages + PAGE_SHIFT - 3);
 	cm->allowed_sects = __cow_calculate_allowed_sects(cache_size, cm->total_sects);
 	cm->data_offset = COW_HEADER_SIZE + (cm->total_sects * (sect_size*8));
 	cm->curr_pos = cm->data_offset / COW_BLOCK_SIZE;
+	cm->file_max = file_max + cm->data_offset;
```
Comment (skypodolsky) [inline src/elastio-snap.c:2912]: If `fallocate` is not specified, we calculate the cow file size as 10% of the disk volume. If we do that, we actually want it to be, well, 10% instead of 10% - memory for section storage. The section storage isn't huge, can be like 1-50 MB depending on disk capacity. But we promised 10% for **data** to be stored and I wouldn't like to implicitly steal some of this memory.

File: src/elastio-snap.c [hunk 10]
```diff
@@ -1830,29 +1833,35 @@ int file_write_block(struct snap_device *dev, void *block, size_t offset, size_t
...
-
-	if (dev->sd_cow)
-		file_unlock(dev->sd_cow->filp);
+	WARN_ON(len > SECTORS_PER_BLOCK);
 
 write_bio:
 	start_sect = sector_by_offset(dev, offset);
+	if (start_sect == SECTOR_INVALID) {
+		LOG_WARN("Possible write IO to the end of file (offset=%lu)", offset);
+		goto out;
```
Comment (skypodolsky) [inline src/elastio-snap.c:1850]: No need to return errors, all critical events are handled by outside logic. Despite that, there is a valid scenario, when this return is needed. Suppose you're trying to write the last block (4k, 8 sectors) to the disk, but there are only a couple of sectors left. If you don't handle this, you will end up with 'attempt write beyond the end of device', which is definitely not something you'd like to see.

File: src/elastio-snap.c [hunk 11]
```diff
@@ -4557,17 +4651,18 @@ static int __tracer_setup_cow(struct snap_device *dev, struct block_device *bdev
...
-				dev->sd_falloc_size = fallocated_space;
 			}
 
 			//create and open the cow manager
 			LOG_DEBUG("creating cow manager");
 			ret = cow_init(dev, cow_path_full, SECTOR_TO_BLOCK(size), COW_SECTION_SIZE, dev->sd_cache_size, max_file_size, uuid, seqid, &dev->sd_cow);
 			if(ret) goto error;
+
+			dev->sd_falloc_size = dev->sd_cow->file_max;
+			do_div(dev->sd_falloc_size, (1024 * 1024));
```
Comment (skypodolsky) [inline src/elastio-snap.c:4664]: We update `dev->sd_cow->file_max` in `cow_init`, so I've put this code here to update `dev->sd_falloc_size` appropriately

File: tests/test_transition_incremental.py [hunk 12]
```diff
@@ -61,7 +66,7 @@ def test_transition_fs_sync_cow_full(self):
         self.assertIsNotNone(snapdev)
 
         self.assertEqual(snapdev["error"], -errno.EFBIG)
-        self.assertEqual(snapdev["state"], elastio_snap.State.ACTIVE | elastio_snap.State.SNAPSHOT)
```
Comment (skypodolsky) [inline tests/test_transition_incremental.py:64]: The driver can clear the SNAPSHOT bit, so we just check for ACTIVE. The presence of SNAPSHOT isn't important anymore, as the driver is in the fail state.

File: tests/test_transition_incremental.py [hunk 13]
```diff
@@ -61,7 +66,7 @@ def test_transition_fs_sync_cow_full(self):
...
+        self.assertTrue(snapdev["state"] & elastio_snap.State.ACTIVE)
```
Comment (skypodolsky) [inline tests/test_transition_incremental.py:69]: The driver can clear the SNAPSHOT bit, so we just check for ACTIVE. The presence of SNAPSHOT isn't important anymore, as the driver is in the fail state.

**Review by vsazhenyuk-softheme — APPROVED** [review]

File: tests/test_transition_incremental.py (hunk 13 above)
Comment (e-kov) [reply tests/test_transition_incremental.py:69]: It's hard to agree. I need some clarification.
It seems that the `SNAPSHOT` bit means that the snapshot device `/dev/elastio-snap[MINOR]` exists. In case of `elastio` and memory mapping and "ignore snap errors" parameter it's pretty much important to have this snapshot device present and w/o IO errors.
If the snapshot device `/dev/elastio-snap[MINOR]` can exist and exists when `SNAPSHOT` bit is not set. Let's assume this case. Then it's like OK (safe situation) for `elastio` and it should not be killed by `SIGBUS`. But in this case we have inconsistent real state and logical state of the snapshot device.

**Review by e-kov — COMMENTED** [review]
:+1:

File: tests/test_snapshot.py [hunk 14]
```diff
@@ -61,7 +78,6 @@ def test_track_writes(self):
         os.sync()
         info = elastio_snap.info(self.minor)
         start_nr = info["nr_changed_blocks"]
-        self.assertNotEqual(start_nr, 0)
```
[the remark this answers is not in the document]
Comment (e-kov) [reply tests/test_snapshot.py:64]: Yep, according to the test, there is no any write after the setup snapshot operation. So this assert is doubtful. But it was here for some purpose. That's why I wonder do you have an idea why it was here if it's removed )

File: tests/test_multipart.py [hunk 15]
```diff
@@ -81,23 +87,31 @@ def test_multipart_setup_volumes_write_last_after_destroy(self):
...
-            os.sync()
             md5_orig = util.md5sum(testfile)
 
             self.assertEqual(elastio_snap.setup(self.minors[i], self.devices[i], self.cow_full_paths[i]), 0)
-            self.addCleanup(elastio_snap.destroy, self.minors[i])
+            os.sync()
 
-            with open(testfile, "w") as f:
-                f.write("jumps over the lazy dog")
+            self.addCleanup(elastio_snap.destroy, self.minors[i])
```
[the remark this answers is not in the document]
Comment (e-kov) [reply tests/test_multipart.py:110]: Not critical, but let's try to use a single sync ) just for the beauty of the code )

File: tests/test_snapshot.py [hunk 16]
```diff
@@ -51,7 +69,6 @@ def test_modify_origin(self):
         self.assertEqual(md5_orig, md5_snap)
 
     @unittest.skipIf(os.getenv('TEST_FS') == "ext2" and int(platform.release().split(".", 1)[0]) < 4, "Broken on ext2, 3-rd kernels")
-    @unittest.skipIf(os.getenv('TEST_FS') == "xfs", "Broken on XFS, due to ignored os.sync and due to #63.")
     def test_track_writes(self):
```
[the remark this answers is not in the document]
Comment (e-kov) [reply tests/test_snapshot.py:71]: Ah, I see. Sorry, lost in the changes. The skip for `ext2` has been removed. Perfect! :+1:

File: tests/test_transition_incremental.py (hunk 13 above)
Comment (e-kov) [reply tests/test_transition_incremental.py:69]: Ah, I see. We are checking there result of the `transition_to_incremental~ as 
`self.assertTrue(err == errno.EINVAL or err == errno.EFBIG)` 
Probably different errors may be results of the different failure stages.
Ok then. Let's add a comment
```python
# SNAPSHOT bit is not checked because it's may or may not be set 
# dependently on the place of the failure in transition_to_incremental().
# But ACTIVE bit should be present in any case.
self.assertTrue(snapdev["state"] & elastio_snap.State.ACTIVE)
```

Comment (skypodolsky) [reply tests/test_transition_incremental.py:73]: Done.

File: tests/test_snapshot.py [hunk 17]
```diff
@@ -24,24 +25,41 @@ def setUp(self):
...
         self.assertEqual(elastio_snap.setup(self.minor, self.device, self.cow_full_path), 0)
+        os.sync()
         self.addCleanup(elastio_snap.destroy, self.minor)
 
-        with open(testfile, "w") as f:
-            f.write("jumps over the lazy dog")
-
+        util.dd("/dev/urandom", testfile, file_size_mb, bs="1M")
         os.sync()
+
```
[the remark this answers is not in the document]
Comment (skypodolsky) [reply tests/test_snapshot.py]: Fixed.

**Review by e-kov — APPROVED** [review]
:+1:
