### PR TITLE
Fixed attempt to access beyond end of device

### LINKED ISSUE #150: attempt to access beyond end of device on Ubuntu 22.04 aarch64 LVM XFS
The tests are hanging time to time on Ubuntu 22.04 aarch64, LVM, XFS:

```
elastio-snap: 
kernel: 5.15.0-37-generic
filesystem: xfs
gcc: 11.2.0-19ubuntu1)
bash: 5.1.16(1)-release
python: Python 3.10.4
  Physical volume "/dev/loop3p1" successfully created.
  Physical volume "/dev/loop4p1" successfully created.
  Volume group "vg_mirror13" successfully created
  Rounding up size to full physical extent 232.00 MiB
  Logical volume "lv_mirror13" created.
test_destroy_active_incremental (test_destroy.TestDestroy) ... ok
test_destroy_active_snapshot (test_destroy.TestDestroy) ... ok
test_destroy_dormant_incremental (test_destroy.TestDestroy) ... ok
test_destroy_dormant_snapshot (test_destroy.TestDestroy) ... ok
test_destroy_nonexistent_device (test_destroy.TestDestroy) ... ok
test_destroy_unverified_incremental (test_destroy.TestDestroy) ... skipped 'Broken Ubuntu 22.04 with kernel 5.15 (see #138)'
test_destroy_unverified_snapshot (test_destroy.TestDestroy) ... skipped 'Broken Ubuntu 22.04 with kernel 5.15 (see #138)'
  Logical volume "lv_mirror13" successfully removed
  Volume group "vg_mirror13" successfully removed
  Physical volume "/dev/loop3p1" successfully created.
  Physical volume "/dev/loop4p1" successfully created.
  Volume group "vg_mirror22" successfully created
  Rounding up size to full physical extent 232.00 MiB
  Logical volume "lv_mirror22" created.
Error: The action has timed out.
```

dmesg contains
```
...
[  456.716756] attempt to access beyond end of device
               vda2: rw=0, want=207537928, limit=207509504
[  456.749981] elastio-snap: error reading from base device for copy on write: -5
[  456.750513] attempt to access beyond end of device
               vda2: rw=0, want=207535104, limit=207509504
...
[  621.294087] Buffer I/O error on dev elastio-snap20, logical block 25938672, async page read
```
Full dmesg: [dmesg_u2204_arm.log](https://github.com/elastio/elastio-snap/files/9154033/dmesg_u2204_arm.log)

### PR DESCRIPTION
**Pull request by skypodolsky**
This fix closes #150 and _properly_ approaches the integration of the v5.16 Linux kernel.

Previously, during the integration of the v5.16 kernel, we had an issue with the partition mounting (`test_modify_origin` couldn't pass successfully). This issue was caused by the wrong sector offset calculation. Then it was [incorrectly] considered to be a new, changed approach to the sector calculation in the modern kernel. Now we see that understanding wasn't correct.

During debugging of issue #150, a similar behavior's been found on v5.15 (ubuntu 22.04, arm64). It was found that the issue is not related to the 5.16. Hence, the solution made during that time was rather a workaround and didn't actually explain the nature of the problem.

After proper debugging, it was seen that some bio requests were processed OK, while the others had the same offset problem. It was suspected that the bug may be related to the bio's nature (depending on the issuing entity). This was confirmed: indeed, the problem was with the absent flags, that have been introduced after v5.11 (or somewhere around). This explains random failures: it seems that sometimes bio requests were issued with proper partition remapping, and sometimes not. These random differences made up the problem with the wrong offsets.

This was fixed by copying the relevant flags in `make_read_clone`. Additional compats for new kernels have been added as well.

Closes #150

### CODE REVIEW

File: src/elastio-snap.c [hunk 1]
```diff
@@ -2867,12 +2866,14 @@ static int bio_make_read_clone(struct block_device *bdev, struct bio_set *bs, st
...
-	 */
-	new_bio->bi_bdev = new_bio->bi_bdev->bd_disk->part0;
+#if defined HAVE_BIO_REMAPPED
+	if (bio_flagged(orig_bio, BIO_REMAPPED))
+		bio_set_flag(new_bio, BIO_REMAPPED);
+#endif
+
+#if defined HAVE_BIO_THROTTLED
+	if (bio_flagged(orig_bio, BIO_THROTTLED))
+		bio_set_flag(new_bio, BIO_THROTTLED);
```
Comment (e-kov) [inline src/elastio-snap.c:2876]: It would be great to leave here some comment about influence of these flags to the attempt to access beyond end of device =)

File: src/configure-tests/feature-tests/bio_remapped.c [hunk 2]
```diff
@@ -0,0 +1,14 @@
+// SPDX-License-Identifier: GPL-2.0-only
+
+/*
+ * Copyright (C) 2020 Elastio Software Inc.
```
Comment (e-kov) [inline src/configure-tests/feature-tests/bio_remapped.c:4]: https://github.com/elastio/elastio-snap/pull/160#discussion_r947629549

File: src/configure-tests/feature-tests/bio_throttled.c [hunk 3]
```diff
@@ -0,0 +1,14 @@
+// SPDX-License-Identifier: GPL-2.0-only
+
+/*
+ * Copyright (C) 2020 Elastio Software Inc.
```
Comment (e-kov) [inline src/configure-tests/feature-tests/bio_throttled.c:4]: https://github.com/elastio/elastio-snap/pull/160#discussion_r947629549

File: src/configure-tests/feature-tests/bio_remapped.c [hunk 4]
```diff
@@ -0,0 +1,14 @@
...
+ */
+
```
Comment (e-kov) [inline src/configure-tests/feature-tests/bio_remapped.c:6]: It would be great to have a comment here about kernel version from which this test is necessary, like here
https://github.com/elastio/elastio-snap/blob/de9e6bde084c1cb2fa9fde9f557a7f44388501f0/src/configure-tests/feature-tests/bio_free_pages.c#L7
or here https://github.com/elastio/elastio-snap/blob/de9e6bde084c1cb2fa9fde9f557a7f44388501f0/src/configure-tests/feature-tests/proc_create_fn_file_operations.c#L8
These comments are not present in all feature tests, but we try to include them in new tests we add.

File: src/configure-tests/feature-tests/bio_throttled.c [hunk 5]
```diff
@@ -0,0 +1,14 @@
...
+ */
+
```
Comment (e-kov) [inline src/configure-tests/feature-tests/bio_throttled.c:6]: Same about kernel version comment.

**Review by e-kov — COMMENTED** [review]
It would be great to cover this fix by tests. The easiest way is to increase count of partitions in the "multipart" tests from 2 to 5. These tests are failing on 5 partitions without this fix and should not fail with the fix.
https://github.com/elastio/elastio-snap/blob/de9e6bde084c1cb2fa9fde9f557a7f44388501f0/tests/devicetestcase_multipart.py#L22-L23

**Review by vsazhenyuk-softheme — APPROVED** [review]

File: src/elastio-snap.c (hunk 1 above)
Comment (skypodolsky) [reply src/elastio-snap.c:2884]: Done.

File: src/configure-tests/feature-tests/bio_throttled.c (hunk 5 above)
Comment (skypodolsky) [reply src/configure-tests/feature-tests/bio_throttled.c:6]: Done.

File: src/configure-tests/feature-tests/bio_remapped.c (hunk 4 above)
Comment (skypodolsky) [reply src/configure-tests/feature-tests/bio_remapped.c:6]: Done.

**Review by e-kov — COMMENTED** [review]
Ally my comments are addressed except the main one about tests =)
https://github.com/elastio/elastio-snap/pull/161#pullrequestreview-1082259857

**Review by anelson — APPROVED** [review]

**Review by e-kov — APPROVED** [review]
Great fix! :+1:
